### ISSUE TITLE
assets fail to create from stack for eu-central-1

### ISSUE THREAD

**Issue by ElishaVladimirsky** [aws-samples/aws-bookstore-demo-app#36]
Stack creation fails for 2 assets, bookstoreNeptuneLoader and BooksUploader, on eu-central-1. as far as I can see there is a problem accessing a public s3 bucket for some node modual in aws-sdk. im not certin if there is some problem with settings on my account that prevent that bucket from being accessed or there is a problem with the stack template itself.

log snippet of the error:

2022-10-31T13:17:34.177Z	3e2dc1b4-716d-48e4-87b9-2b00108ee0e2	INFO	AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:710:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
  region: null,
  time: 2022-10-31T13:17:34.117Z,
  requestId: '59E0FHNJ3A602C4T',
  extendedRequestId: 'JbFqg75W3vJ+ey7aj8IlKvDnRoOq07dVV7wW7OlYZXWFw8bpOKAkBzj0AJczeZZGe8gR5UNceTI=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 19.55702681850291
}

i just tried to create the stack on eu-central-1, no changes to anything just ran the stack. any help would be greatly appriciated.

**Comment by triggan** [comment]
Thanks for reporting the issue.  Are you launching the stack from the Launch Stack buttons located here? https://github.com/aws-samples/aws-bookstore-demo-app#getting-started

Are the logs above from the UploadBooks function? (the bookstoreNeptuneLoader is using Python)

The UploadBooks function is pulling down a JSON from the following path:
s3://aws-bookstore-demo-app-eu-central-1/data/books.json

The bookstoreNeptuneLoader function is pulling data from:
s3://bookstore-neptune-eu-central-1/data/

Maybe check that you can access the data in both of those locations from your account.  The former bucket is not fully public, but the books.json object has public-read allowed.  The latter bucket is publicly readable, so you should be able to list all of the objects within that prefix.

**Comment by ElishaVladimirsky** [comment]
Thanks for the quick reply.

`Thanks for reporting the issue. Are you launching the stack from the Launch Stack buttons located here? https://github.com/aws-samples/aws-bookstore-demo-app#getting-started`
 Yes we selec eu-cantral-1

`Are the logs above from the UploadBooks function? (the bookstoreNeptuneLoader is using Python)`
yes log was taken from the UploadBooks function.

```
The UploadBooks function is pulling down a JSON from the following path:
s3://aws-bookstore-demo-app-eu-central-1/data/books.json 
```

Tried pulling the file - Got the following error:
2022-11-02 14:48:33,831 - MainThread - awscli.customizations.s3.results - DEBUG - Exception caught during command execution: An error occurred (403) when calling the HeadObject operation: Forbidden
Traceback (most recent call last):
  File "awscli\customizations\s3\s3handler.py", line 149, in call
  File "awscli\customizations\s3\fileinfobuilder.py", line 31, in call
  File "awscli\customizations\s3\filegenerator.py", line 142, in call
  File "awscli\customizations\s3\filegenerator.py", line 318, in list_objects
  File "awscli\customizations\s3\filegenerator.py", line 355, in _list_single_object
  File "awscli\botocore\client.py", line 281, in _api_call
  File "awscli\botocore\client.py", line 609, in _make_api_call
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

```
The bookstoreNeptuneLoader function is pulling data from:
s3://bookstore-neptune-eu-central-1/data/
```
when trying to list the data i recieve:

aws s3 ls s3://bookstore-neptune-eu-central-1/data/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

i recieve 403 for both locations. any ideas on what can cause it?

**Comment by triggan** [comment]
There must be something in your account blocking access to these buckets.  Perhaps an IAM policy that restricts access only to a set of known buckets.

If you open a private browsing window via your browser, you should be able to access:  https://s3.eu-central-1.amazonaws.com/aws-bookstore-demo-app-eu-central-1/data/books.json   (which shows that this object is set for public-read)

Or you could do the same via:

```
aws s3 cp s3://aws-bookstore-demo-app-eu-central-1/data/books.json ./ --no-sign-request
```

If you run the s3 cli commands with `--no-sign-request` it should pass an anonymous (unsigned) request and allow you to see what is in that bucket/prefix:

```
aws s3 ls s3://bookstore-neptune-eu-central-1/data/ --no-sign-request
```

**Comment by triggan** [comment]
This was found to be an issue with the configuration of an [AWS Service Control Policy](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html) (SCP).  For anyone that stumbles upon this in the future, be sure to check all related IAM and SCP policies to ensure proper access before deploying this stack.
